package club.zqg.prision.dao;

import club.zqg.prision.domain.PrisionPolice;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface PrisionPoliceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prision_police
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    int deleteByPrimaryKey(Integer policeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prision_police
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    int insert(PrisionPolice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prision_police
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    PrisionPolice selectByPrimaryKey(Integer policeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prision_police
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    List<PrisionPolice> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prision_police
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    int updateByPrimaryKey(PrisionPolice record);
}