package club.zqg.prision.dao;

import club.zqg.prision.domain.PrisionChief;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface PrisionChiefMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prision_chief
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    int deleteByPrimaryKey(Integer chiefId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prision_chief
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    int insert(PrisionChief record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prision_chief
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    PrisionChief selectByPrimaryKey(Integer chiefId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prision_chief
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    List<PrisionChief> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prision_chief
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    int updateByPrimaryKey(PrisionChief record);
}