package club.zqg.prision.dao;

import club.zqg.prision.domain.PrisionRank;
import org.springframework.stereotype.Repository;

import java.util.List;


@Repository
public interface PrisionRankMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prision_rank
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    int deleteByPrimaryKey(Short rankId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prision_rank
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    int insert(PrisionRank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prision_rank
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    PrisionRank selectByPrimaryKey(Short rankId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prision_rank
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    List<PrisionRank> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prision_rank
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    int updateByPrimaryKey(PrisionRank record);
}