package club.zqg.prision.dao;

import club.zqg.prision.domain.Prisioner;
import org.springframework.stereotype.Repository;

import java.util.List;


@Repository
public interface PrisionerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prision_prisioner
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    int deleteByPrimaryKey(Integer prisionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prision_prisioner
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    int insert(Prisioner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prision_prisioner
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    Prisioner selectByPrimaryKey(Integer prisionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prision_prisioner
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    List<Prisioner> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prision_prisioner
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    int updateByPrimaryKey(Prisioner record);
}