package club.zqg.prision.dao;

import club.zqg.prision.domain.PrisionNews;
import org.springframework.stereotype.Repository;

import java.util.List;


@Repository
public interface PrisionNewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prision_news
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    int deleteByPrimaryKey(Short newsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prision_news
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    int insert(PrisionNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prision_news
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    PrisionNews selectByPrimaryKey(Short newsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prision_news
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    List<PrisionNews> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prision_news
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    int updateByPrimaryKey(PrisionNews record);
}