package club.zqg.prision.domain;

public class PrisionPolice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prision_police.police_id
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    private Integer policeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prision_police.police_name
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    private String policeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prision_police.rank_id
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    private Short rankId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prision_police.area_id
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    private Short areaId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prision_police.police_id
     *
     * @return the value of prision_police.police_id
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    public Integer getPoliceId() {
        return policeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prision_police.police_id
     *
     * @param policeId the value for prision_police.police_id
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    public void setPoliceId(Integer policeId) {
        this.policeId = policeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prision_police.police_name
     *
     * @return the value of prision_police.police_name
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    public String getPoliceName() {
        return policeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prision_police.police_name
     *
     * @param policeName the value for prision_police.police_name
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    public void setPoliceName(String policeName) {
        this.policeName = policeName == null ? null : policeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prision_police.rank_id
     *
     * @return the value of prision_police.rank_id
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    public Short getRankId() {
        return rankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prision_police.rank_id
     *
     * @param rankId the value for prision_police.rank_id
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    public void setRankId(Short rankId) {
        this.rankId = rankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prision_police.area_id
     *
     * @return the value of prision_police.area_id
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    public Short getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prision_police.area_id
     *
     * @param areaId the value for prision_police.area_id
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    public void setAreaId(Short areaId) {
        this.areaId = areaId;
    }
}