package club.zqg.prision.domain;

public class PrisionArea {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prision_area.area_id
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    private Short areaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prision_area.area_name
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    private String areaName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prision_area.area_id
     *
     * @return the value of prision_area.area_id
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    public Short getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prision_area.area_id
     *
     * @param areaId the value for prision_area.area_id
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    public void setAreaId(Short areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prision_area.area_name
     *
     * @return the value of prision_area.area_name
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prision_area.area_name
     *
     * @param areaName the value for prision_area.area_name
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }
}