package club.zqg.prision.domain;

public class PrisionChief {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prision_chief.chief_id
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    private Integer chiefId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prision_chief.chief_name
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    private String chiefName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prision_chief.chief_rank_id
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    private Short chiefRankId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prision_chief.chief_id
     *
     * @return the value of prision_chief.chief_id
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    public Integer getChiefId() {
        return chiefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prision_chief.chief_id
     *
     * @param chiefId the value for prision_chief.chief_id
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    public void setChiefId(Integer chiefId) {
        this.chiefId = chiefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prision_chief.chief_name
     *
     * @return the value of prision_chief.chief_name
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    public String getChiefName() {
        return chiefName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prision_chief.chief_name
     *
     * @param chiefName the value for prision_chief.chief_name
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    public void setChiefName(String chiefName) {
        this.chiefName = chiefName == null ? null : chiefName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prision_chief.chief_rank_id
     *
     * @return the value of prision_chief.chief_rank_id
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    public Short getChiefRankId() {
        return chiefRankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prision_chief.chief_rank_id
     *
     * @param chiefRankId the value for prision_chief.chief_rank_id
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    public void setChiefRankId(Short chiefRankId) {
        this.chiefRankId = chiefRankId;
    }
}