package club.zqg.prision.domain;

public class PrisionRank {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prision_rank.rank_id
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    private Short rankId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prision_rank.rank_name
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    private String rankName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prision_rank.rank_id
     *
     * @return the value of prision_rank.rank_id
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    public Short getRankId() {
        return rankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prision_rank.rank_id
     *
     * @param rankId the value for prision_rank.rank_id
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    public void setRankId(Short rankId) {
        this.rankId = rankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prision_rank.rank_name
     *
     * @return the value of prision_rank.rank_name
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    public String getRankName() {
        return rankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prision_rank.rank_name
     *
     * @param rankName the value for prision_rank.rank_name
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    public void setRankName(String rankName) {
        this.rankName = rankName == null ? null : rankName.trim();
    }
}