package club.zqg.prision.domain;

public class PrisionNews {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prision_news.news_id
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    private Short newsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prision_news.news_content
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    private String newsContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prision_news.news_id
     *
     * @return the value of prision_news.news_id
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    public Short getNewsId() {
        return newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prision_news.news_id
     *
     * @param newsId the value for prision_news.news_id
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    public void setNewsId(Short newsId) {
        this.newsId = newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prision_news.news_content
     *
     * @return the value of prision_news.news_content
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    public String getNewsContent() {
        return newsContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prision_news.news_content
     *
     * @param newsContent the value for prision_news.news_content
     *
     * @mbg.generated Wed Apr 24 21:27:31 CST 2019
     */
    public void setNewsContent(String newsContent) {
        this.newsContent = newsContent == null ? null : newsContent.trim();
    }
}